### ISSUE TITLE
Не выполняется шаг из инструкции: подключите репозиторий к своему git серверу (GitHub, Bitbucket, GitLab, etc)

### ISSUE THREAD

**Issue by andrewzola** [vanessa-opensource/vanessa-bootstrap#3]
При выполнениии 
git remote add origin git remote add origin git://new.url.here
ошибка:
fatal: remote origin already exists.

потому что в .git\config уже есть область [remote "origin"] со ссылкой на этот репозиторий

**Comment by artbear** [comment]
@andrewzola вроде бы правильная последовательность описана

* подпишитесь на обновление шаблона

```Shell
git remote add -f --no-tags -m --mirror bootstrap https://github.com/vanessa-opensource/vanessa-bootstrap.git
```

* подключите репозиторий к своему git серверу (GitHub, Bitbucket, GitLab, etc)

```Shell
git remote add origin git://new.url.here
```

- сначала изменяем имя с ориджин на бутстрап
- потом добавляем ориджин

что не так?

**Comment by andrewzola** [comment]
Еще раз воспроизвел на пустом репозитории:

После выполнения:
git clone https://github.com/vanessa-opensource/vanessa-bootstrap.git .
git remote add -f --no-tags -m --mirror bootstrap https://github.com/vanessa-opensource/vanessa-bootstrap.git
в файле .git\config остается область с таким содержанием
[remote "origin"]
	url = https://github.com/vanessa-opensource/vanessa-bootstrap.git
	fetch = +refs/heads/*:refs/remotes/origin/*

пока я ее не удаляю, выполнить 
git remote add origin git://new.url.here не получается из-за ошибки
fatal: remote origin already exists.

**Comment by andrewzola** [comment]
https://github.com/vanessa-opensource/vanessa-bootstrap/commit/f80d337dfc62056649bbb322a99aa3f53433e6e4

Спасибо
